#!/bin/bash

echo "=== Firebase Firestore Rules Deployment Guide ==="
echo ""
echo "1. Make sure you're logged into Firebase CLI:"
echo "   firebase login"
echo ""
echo "2. Check your current project:"
echo "   firebase use"
echo ""
echo "3. If needed, set your project:"
echo "   firebase use your-project-id"
echo ""
echo "4. Deploy the updated Firestore rules:"
echo "   firebase deploy --only firestore:rules"
echo ""
echo "5. Verify the deployment:"
echo "   firebase firestore:rules:get"
echo ""
echo "=== Current Firestore Rules File ==="
cat firestore.rules
echo ""
echo "=== End of Rules File ==="
echo ""
echo "The key changes made to fix the seat booking issue:"
echo "- Changed 'allow list: if isAdmin();' to 'allow list: if isAuthenticated();'"
echo "- This allows any authenticated user to query bookings for seat availability"
echo "- Added seats collection rules for future use"
echo ""
echo "Run the deployment command manually if the automated deployment didn't work."
