// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCymArTedkhCcSfJIyEk980g41yjPCBVfc',
    appId: '1:22425718047:web:816d7663230cf8e3ddb42a',
    messagingSenderId: '22425718047',
    projectId: 'cinec-movie-app',
    authDomain: 'cinec-movie-app.firebaseapp.com',
    storageBucket: 'cinec-movie-app.firebasestorage.app',
    measurementId: 'G-LT819Q6KKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-bKvo76AM8VGiJ-_DaYy103PjDQOqoNs',
    appId: '1:22425718047:android:d14a3497a666d7b1ddb42a',
    messagingSenderId: '22425718047',
    projectId: 'cinec-movie-app',
    storageBucket: 'cinec-movie-app.firebasestorage.app',
  );

  // For desktop platforms, use web configuration
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCymArTedkhCcSfJIyEk980g41yjPCBVfc',
    appId: '1:22425718047:web:816d7663230cf8e3ddb42a',
    messagingSenderId: '22425718047',
    projectId: 'cinec-movie-app',
    authDomain: 'cinec-movie-app.firebaseapp.com',
    storageBucket: 'cinec-movie-app.firebasestorage.app',
    measurementId: 'G-LT819Q6KKY',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCymArTedkhCcSfJIyEk980g41yjPCBVfc',
    appId: '1:22425718047:web:a2d6cf93f091f8eeddb42a',
    messagingSenderId: '22425718047',
    projectId: 'cinec-movie-app',
    authDomain: 'cinec-movie-app.firebaseapp.com',
    storageBucket: 'cinec-movie-app.firebasestorage.app',
    measurementId: 'G-KL9N6X9KMH',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVtKmxM379h03tUSOGSO2TcbtL8zdhTcw',
    appId: '1:22425718047:ios:a5f501ec27343c84ddb42a',
    messagingSenderId: '22425718047',
    projectId: 'cinec-movie-app',
    storageBucket: 'cinec-movie-app.firebasestorage.app',
    iosBundleId: 'com.example.cinecMovieApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVtKmxM379h03tUSOGSO2TcbtL8zdhTcw',
    appId: '1:22425718047:ios:a5f501ec27343c84ddb42a',
    messagingSenderId: '22425718047',
    projectId: 'cinec-movie-app',
    storageBucket: 'cinec-movie-app.firebasestorage.app',
    iosBundleId: 'com.example.cinecMovieApp',
  );

}